server:
  port: 8080

--- ## Eureka
eureka:
  client:
    service-url:
      defaultZone: http://discovery-eureka:8761/eureka


--- ## db 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-auth:3306/auth
    username: root
    password: 1234

  data:
    redis:
      host: redis
      port: 6379
      password: 1234

--- ## secret 관련
oauth:
  naver:
    app-key: OhHssSBOwmc929lDfGOg
    secret: JIZ1uNAFt7
  kakao:
    app-key: 5b085c799bdb7da9923e226b6a8b6188
    secret: tGusphDWBKePGSVjyGqY5ElI0jkvzRBj

secret:
  accessToken: test1
  refreshToken: test2
  passwordChangeToken: test3

---
## 파일 사이즈
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB


--- # kafka 설정
#spring:
#  kafka:
#    bootstrap-servers: kafka:9092
#    consumer:
#      auto-offset-reset: earliest
