spring:
  application:
    name: auth-service

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true


springdoc:
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    persist-authorization: true
  pre-loading-enabled: true

oauth:
  naver:
    app-key: OhHssSBOwmc929lDfGOg
    secret: JIZ1uNAFt7
  kakao:
    app-key: 5b085c799bdb7da9923e226b6a8b6188
    secret: tGusphDWBKePGSVjyGqY5ElI0jkvzRBj

secret:
  accessToken: test1
  refreshToken: test2