server:
  port: 8080

--- ## Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-eureka:8761/eureka
  instance:
    hostname: auth-service # 쿠버네티스 서비스 명


--- ## db 설정
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-dev:3306/auth
    username: root
    password: 1234

  data:
    redis:
      host: redis
      port: 6379
      password: 1234

    mongodb:
      uri: mongodb://root:1234@mongodb:27017/auth?authSource=admin

  jpa:
    properties:
      hibernate:
        show_sql: true

--- ## secret 관련
oauth:
  naver:
    app-key: OhHssSBOwmc929lDfGOg
    secret: JIZ1uNAFt7
  kakao:
    app-key: 5b085c799bdb7da9923e226b6a8b6188
    secret: tGusphDWBKePGSVjyGqY5ElI0jkvzRBj

secret:
  accessToken: test1
  refreshToken: test2
  passwordChangeToken: test3

---
## 파일 사이즈
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

## 문서화 관련
springdoc:
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    persist-authorization: true
  pre-loading-enabled: true

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

--- # kafka 설정
#spring:
#  kafka:
#    bootstrap-servers: kafka:9092
#    consumer:
#      auto-offset-reset: earliest
