spring:
  application:
    name: auth-service

  profiles:
    default: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

springdoc:
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    persist-authorization: true
  pre-loading-enabled: true

oauth:
  naver:
    app-key: OhHssSBOwmc929lDfGOg
    secret: JIZ1uNAFt7
  kakao:
    app-key: 5b085c799bdb7da9923e226b6a8b6188
    secret: tGusphDWBKePGSVjyGqY5ElI0jkvzRBj

secret:
  accessToken: test1
  refreshToken: test2