server:
  port: 8081

--- ## Eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

--- ## db 설정
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

  data:
    redis:
      port: 6379
      password: 1234

    mongodb:
      uri: mongodb://root:1234@localhost:27017/auth?authSource=admin

--- # kafka 설정
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      auto-offset-reset: earliest

--- ## secret
oauth:
  naver:
    app-key: OhHssSBOwmc929lDfGOg
    secret: JIZ1uNAFt7
  kakao:
    app-key: 5b085c799bdb7da9923e226b6a8b6188
    secret: tGusphDWBKePGSVjyGqY5ElI0jkvzRBj

secret:
  accessToken: test1
  refreshToken: test2
  passwordChangeToken: test3

---
## 파일 사이즈
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB


## 문서화
springdoc:
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    persist-authorization: true
  pre-loading-enabled: true

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

logging:
  level:
    com.example.authserver: DEBUG

