spring:
  application:
    name: api-gateway

  profiles:
    default: dev

  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter

      routes:
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
          filters:
            - name: PathPrefixRemoveFilter
              args:
                prefix: /board-service
            - name: TokenValidateFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - name: PathPrefixRemoveFilter
              args:
                prefix: /auth-service



secret:
  accessToken: test1
  refreshToken: test2