server:
  port: 8080

eureka:
  instance:
    appname: api-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-eureka:8761/eureka