server:
  port: 8000

eureka:
  instance:
    appname: api-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    urls[0]:
      name: 인증/인가 서비스
      url: http://localhost:8000/auth-service/v3/api-docs
    urls[1]:
      name: 식물생활 서비스
      url: http://localhost:8000/board-service/v3/api-docs
    urls[2]:
      name: 내 식물 서비스
      url: http://localhost:8000/my-plant/v3/api-docs
    urls[3]:
      name: 싹싹도감 서비스
      url: http://localhost:8000/encyclo-service/v3/api-docs