spring:
  application:
    name: api-gateway

  profiles:
    default: dev

  cloud:
    gateway:
      default-filters:
        - name: ExceptionHandlerFilter
        - name: LoggingFilter

      routes:
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
          filters:
            - name: PathPrefixRemoveFilter
              args:
                prefix: /board-service
            - name: TokenValidateFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - name: PathPrefixRemoveFilter
              args:
                prefix: /auth-service

        - id: my-plant
          uri: lb://MY-PLANT
          predicates:
            - Path=/my-plant/**
          filters:
            - name: PathPrefixRemoveFilter
              args:
                prefix: /my-plant

secret:
  accessToken: test1
  refreshToken: test2


springdoc:
  webjars:
    prefix:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    use-root-path: true

  cache:
    disabled: true