server:
  port: 8084

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true


scraping-target:
  drfull:
    url: http://localhost:8999