server:
  port: 8080

spring:
  application:
    name: board-service

springdoc:
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    persist-authorization: true
  pre-loading-enabled: true

management:
  endpoint:
    web:
      exposure:
        include: health

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
