spring:
  application:
    name: board-service

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

management:
  endpoint:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    persist-authorization: true
  pre-loading-enabled: true


