server:
  port: 8080

spring:
  application:
    name: board-service


management:
  endpoint:
    web:
      exposure:
        include: health

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

