server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db.com-p.site:33066/plant
    username: root
    password: 1234

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-eureka:8761/eureka
  instance:
    hostname: my-plant # 쿠버네티스 서비스 명
